# Default values for mosquitto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: siemens/sim-edge-app-mosquitto-broker
  tag: 0.1.2.1.3

imagePullPolicy: IfNotPresent

ingress:
  enabled: false

service:
  enabled: true
  type: "ClusterIP"
  port: 1883

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
#  storageClass: standard
  annotations: {}
  
resources:
  requests:
    cpu: 50m
    memory: 100Mi

customResources:
  enablespecificdownload: false
